### ISSUE TITLE
Why set IDF as a feature？

### ISSUE THREAD

**Issue by superSx** [galsang/ABCNN#5]
I think it's no use in Answer selection.

**Comment by galsang** [comment]
I'm not sure now why IDF is used as a feature because it's been a while after I read the article and uploaded the code, but you can refer to 5.2.1 of [the article](https://arxiv.org/pdf/1512.05193.pdf) for details.
Thanks.

> 5.2.1 Task-Specific Setup
We use cosine similarity as the similarity score
for this task. In addition, we use sentence lengths,
WordCnt (count of the number of non-stopwords in
the question that also occur in the answer) and WgtWordCnt
(reweight the counts by the IDF values of
the question words). Thus, the final input to the LR
layer has size k + 4: one cosine for each of the k
blocks and the four additional features
